### ISSUE TITLE
Ignore character in strings

### ISSUE THREAD

**Issue by cassava** [godlygeek/tabular#20]
It would be nice if there was a way for Tabular to ignore the search character when it is found in a string. For example

```
insert into my_table (there, are, four, commas, here)
values ('but if', 1, 'of my strings has the array type:', '{1,2,3,4,5,6,7,8,9}', 'then everything is messed up');
```

Or am I missing something? I imagine that this is not trivial...

**Comment by godlygeek** [comment]
Closing as out of scope.
