### ISSUE TITLE
Getting error Vim(call):E117: Unknow function: tabular#PipeRangeWithOptions

### ISSUE THREAD

**Issue by jojoyuji** [godlygeek/tabular#26]
I was cleaning my .vim/plugin/ since I installed Tabular via pathogen, but suddenly Tabular is not working. 

It outputs the following error: 
`Tabularize: Vim(call):E117: Unknow function: tabular#PipeRangeWithOptions`

**Comment by jaredlwong** [comment]
To anyone that comes across this, I think it's a problem with vundle + tabular, not sure though.

I think vundle isn't autoloading tabular/autoload. But after doing either
```:source ~/.vim/bundle/tabular/autoload/tabular.vim```

or copying `tabular.vim` to `~/.vim/autoload` it seems to work
```
cp ~/.vim/bundle/tabular/autoload/tabular.vim ~/.vim/autoload/
```

**Comment by godlygeek** [comment]
Closing as not an issue, then - though if anyone is still impacted by this, it sounds like what @jaredlwong is describing is a Vundle bug that should be reported to its maintainers.
