### ISSUE TITLE
No matching autocommands error with neovim

### ISSUE THREAD

**Issue by televator** [godlygeek/tabular#47]
When opening neovim with your plugin the "No matching autocommands\n Press ENTER or type command to continue" error shows up no matter if I open an existing file or start from scratch. After I pressed Enter everything seems to be working fine (especially tabular).
My [vimrc.txt](https://github.com/godlygeek/tabular/files/168834/vimrc.txt) is not the shortest, but I tracked the problem down to this plugin.
Runnning on 
Ubuntu 14.04
nvim --version NVIM 0.1.3-dev
latest tabular version

On standard vim no error shows up.
Thanks for the amazing plugin - a great time saver.
Please let me know how I can help resolving this issue.

**Comment by JiriChara** [comment]
I am having the same issue as well since today. There were no changes in this repository for last 3 years so I suppose it's related to some changes in neovim since the plugin works well with vim 7.4. Maybe @tarruda or @Shougo can help?

**Comment by televator** [comment]
Thanks for your input. I just installed tabular yesterday and it never worked, so couldn't really tell where the problem came from. Hope the neovim people have can help.

**Comment by flybayer** [comment]
I've got nvim 0.1.3-dev and also have this same issue.

**Comment by flybayer** [comment]
I've tracked it down to `s:ParsePattern()`'s call to `tabular#ElementFormatPattern()` ([here](https://github.com/godlygeek/tabular/blob/60f25648814f0695eeb6c1040d97adca93c4e0bb/plugin/Tabular.vim#L99))

If I copy the following code from `autoload/tabular.vim` into `plugin/Tabular.vim` right before `s:ParsePattern()`, then I no longer get the "no autocommand" error.

```vim
let s:formatelempat = '\%([lrc]\d\+\)'

function! tabular#ElementFormatPattern()
  return s:formatelempat
endfunction
```

Replacing this line in `s:ParsePattern()`
```vim
let pat = '\\\@<!\%(\\\\\)\{-}\zs/' . tabular#ElementFormatPattern() . '*$'
```
with this one also fixes it.
```vim
let pat = '\\\@<!\%(\\\\\)\{-}\zs/\%([lrc]\d\+\)*$'
```

However, I don't know enough about how plugins work to explain why this is...

**Comment by flybayer** [comment]
Ah ha, so it appears it's actually a NeoVim regression introduced by [this pull request](https://github.com/neovim/neovim/pull/4384).

And the good news is it's already been fixed by the commits at the bottom of that pull request. If you update to the latest neovim, you don't get this warning message anymore.

**Comment by televator** [comment]
yep, looks fine again. Thanks for the info. Closing this.

**Comment by JiriChara** [comment]
:+1:
