### ISSUE TITLE
Beautify Function Signatures Expression

### ISSUE THREAD

**Issue by iasj** [godlygeek/tabular#48]
Hi. Thanks for sharing this awesome plugin, I really enjoy it.

Here is my problem. I've been coding a library in C, and very often I have to put a lot of function signatures somewhere. To help me see things, I want to acomplish the following

![view](https://cloud.githubusercontent.com/assets/7888397/17655780/8cd256ae-6288-11e6-9b10-9caca98e287b.png)

The most important are the parameters. I want them to be organized with their names to the right and their types to the left, with some space from '(', ',' and ')'.
I've been using this expression: `Tabularize /[()]`, in selected text, and I always get this
![view2](https://cloud.githubusercontent.com/assets/7888397/17655851/78ffaf54-6289-11e6-94fb-68dad3ace4f3.png)

which is not what I need. And things get even uglier with more than 2 parameters.

So, I need the right expression rather than `/[()]`, and I really sucks in regex, so I would love some help.

OBS: The function's name goes inside parenthesis, because they are actually pointers to functions inside a struct definition.

**Comment by mb1986** [comment]
Hi, please check this out:
```
Tabularize /[a-zA-Z0-9*_]\+/l1l1l1l1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1l1l1r1l1
```

It should work up to 10 arguments.

**Comment by iasj** [comment]
mb1986. 

Thanks for your quick reply. It worked just fine. Look:

![view](https://cloud.githubusercontent.com/assets/7888397/17684418/d3ad51ec-6331-11e6-9467-2b901fc41744.png)

Thanks a lot for your help.
