### ISSUE TITLE
Feature request: neovim optimizations

### ISSUE THREAD

**Issue by cprn** [godlygeek/tabular#52]
Currently `:Tabularize` on 130MB CSV on platform with i7-2600 CPU takes about 18 minutes utilizing 100% of one core at a time and locking `vim` process in the meantime .

From [Neovim website](https://neovim.io/):
> The msgpack API enables structured communication to and from any programming language. Remote plugins run as co-processes that communicate with Neovim safely and asynchronously.

Please, consider `nvim` specific optimizations in the future.

**Comment by godlygeek** [comment]
If someone submitted a PR that accomplished this without negatively impacting vanilla vim I'd be willing to entertain it, but I don't myself use Neovim and am not personally interested enough to perform Neovim-specific optimizations.

**Comment by cprn** [comment]
Quick question then: does `tabular` use async jobs introduced in Vim 8? I grepped `async` in the code but didn't find anything.

**Comment by godlygeek** [comment]
No, it doesn't.
