### ISSUE TITLE
"Unrecognized command '='"

### ISSUE THREAD

**Issue by DougBeney** [godlygeek/tabular#59]
Haven't used Tabular for a while, but just gave it a try today. Coming across the exact error in the title.

I would:

- Select text using the visual line selection
- Press `:`
- Type `Tab`

I am using NeoVim version 0.2.2 on Linux.

**Comment by godlygeek** [comment]
Unless this reproduces with vanilla vim, I'd expect this is a NeoVim-specific issue. Closing this, but if you can reproduces the problem with vanilla vim I'll reopen.
