### ISSUE TITLE
Incorrectly Formatted Table when | characters are included in the table entries

### ISSUE THREAD

**Issue by alichtman** [godlygeek/tabular#64]
I realize that there is no way for Tabularize to distinguish regular `|` characters that should be treated as text vs. table delimiters. 

But, maybe adding some quote / wrapper (parenthesis, brackets, etc.) detection would allow proper formatting of this table, for instance:

```
# What Tabular does
|  Binding  |         Command                             |
| --------- | --------------------------------------------|
| `<C-w>    |`                                            | Max out the width of the current split      |

# Proper formatting
|  Binding  |         Command                             |
| --------- | --------------------------------------------|
| `<C-w>|`  | Max out the width of the current split      |
```

My implementation suggestion would be parsing each line for certain punctuation (like `"`, `'`, `` ` ``, etc.) and keeping track of matching pairs with a stack. Push when you see a "left" character and pop when there's a matching right character. If you hit a `|` and the stack isn't empty, it's not a table delimiter.

**Comment by jjaderberg** [comment]
Tabular accepts a regex, right? Can't you just provide a better regex than a literal `|` char?

**Comment by alichtman** [comment]
Oh, wow, yeah I totally didn't think this through.

I'm just going to blame this one on the sleep deprivation...

Thanks, @jjaderberg
