### ISSUE TITLE
docs failed: Duplicate tag ":Tabularize" in file Tabular.txt

### ISSUE THREAD

**Issue by kdheepak** [godlygeek/tabular#75]
I get this error `Duplicate tag ":Tabularize" in file Tabular.txt` when updating this plugin using lazy.nvim:

![image](https://github.com/godlygeek/tabular/assets/1813121/e6b9a425-302c-45f1-ad82-513921f64130)

It only happens once during the update. I figured I'd report it since it happened for me on two machines.

**Comment by godlygeek** [comment]
Whoops, sorry - should be fixed now by https://github.com/godlygeek/tabular/commit/12437cd1b53488e24936ec4b091c9324cafee311

**Comment by kdheepak** [comment]
Thanks for the quick fix!

**Comment by godlygeek** [comment]
Thanks for the quick heads up that I broke it! 😅
